import Collatz.TwoRiseCheck

/-!
# Two-rise bounds for the chains of the `m`-cycle exclusions (kernel checks)

Generated by `research/scripts/mcycle101_certgen/gen_lean.py`. Each `AllPairs N B` is
`rangeOK` evaluated by the kernel on chunks of at most 3000 first rises
(`N` = 23446).
-/

set_option Elab.async false

namespace Collatz.TwoRise

theorem tr23446_0 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 1 1 511 = true := by
  decide +kernel

theorem tr23446_1 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 512 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 511 1) 511 = true := by
  decide +kernel

theorem tr23446_2 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 1023 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 1022 1) 511 = true := by
  decide +kernel

theorem tr23446_3 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 1534 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 1533 1) 511 = true := by
  decide +kernel

theorem tr23446_4 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 2045 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 2044 1) 511 = true := by
  decide +kernel

theorem tr23446_5 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 2556 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 2555 1) 511 = true := by
  decide +kernel

theorem tr23446_6 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 3067 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 3066 1) 511 = true := by
  decide +kernel

theorem tr23446_7 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 3578 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 3577 1) 511 = true := by
  decide +kernel

theorem tr23446_8 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 4089 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 4088 1) 511 = true := by
  decide +kernel

theorem tr23446_9 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 4600 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 4599 1) 511 = true := by
  decide +kernel

theorem tr23446_10 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 5111 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 5110 1) 511 = true := by
  decide +kernel

theorem tr23446_11 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 5622 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 5621 1) 511 = true := by
  decide +kernel

theorem tr23446_12 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 6133 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 6132 1) 511 = true := by
  decide +kernel

theorem tr23446_13 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 6644 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 6643 1) 511 = true := by
  decide +kernel

theorem tr23446_14 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 7155 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 7154 1) 511 = true := by
  decide +kernel

theorem tr23446_15 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 7666 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 7665 1) 511 = true := by
  decide +kernel

theorem tr23446_16 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 8177 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 8176 1) 511 = true := by
  decide +kernel

theorem tr23446_17 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 8688 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 8687 1) 511 = true := by
  decide +kernel

theorem tr23446_18 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 9199 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 9198 1) 511 = true := by
  decide +kernel

theorem tr23446_19 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 9710 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 9709 1) 511 = true := by
  decide +kernel

theorem tr23446_20 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 10221 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 10220 1) 511 = true := by
  decide +kernel

theorem tr23446_21 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 10732 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 10731 1) 511 = true := by
  decide +kernel

theorem tr23446_22 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 11243 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 11242 1) 511 = true := by
  decide +kernel

theorem tr23446_23 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 11754 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 11753 1) 511 = true := by
  decide +kernel

theorem tr23446_24 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 12265 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 12264 1) 511 = true := by
  decide +kernel

theorem tr23446_25 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 12776 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 12775 1) 511 = true := by
  decide +kernel

theorem tr23446_26 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 13287 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 13286 1) 511 = true := by
  decide +kernel

theorem tr23446_27 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 13798 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 13797 1) 511 = true := by
  decide +kernel

theorem tr23446_28 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 14309 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 14308 1) 511 = true := by
  decide +kernel

theorem tr23446_29 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 14820 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 14819 1) 511 = true := by
  decide +kernel

theorem tr23446_30 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 15331 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 15330 1) 511 = true := by
  decide +kernel

theorem tr23446_31 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 15842 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 15841 1) 511 = true := by
  decide +kernel

theorem tr23446_32 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 16353 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 16352 1) 511 = true := by
  decide +kernel

theorem tr23446_33 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 16864 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 16863 1) 511 = true := by
  decide +kernel

theorem tr23446_34 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 17375 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 17374 1) 511 = true := by
  decide +kernel

theorem tr23446_35 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 17886 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 17885 1) 511 = true := by
  decide +kernel

theorem tr23446_36 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 18397 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 18396 1) 511 = true := by
  decide +kernel

theorem tr23446_37 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 18908 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 18907 1) 511 = true := by
  decide +kernel

theorem tr23446_38 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 19419 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 19418 1) 511 = true := by
  decide +kernel

theorem tr23446_39 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 19930 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 19929 1) 511 = true := by
  decide +kernel

theorem tr23446_40 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 20441 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 20440 1) 511 = true := by
  decide +kernel

theorem tr23446_41 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 20952 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 20951 1) 511 = true := by
  decide +kernel

theorem tr23446_42 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 21463 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 21462 1) 511 = true := by
  decide +kernel

theorem tr23446_43 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 21974 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 21973 1) 511 = true := by
  decide +kernel

theorem tr23446_44 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 22485 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 22484 1) 511 = true := by
  decide +kernel

theorem tr23446_45 : rangeOK 23446 23458 16 46988 ((2 ^ (46988 + 1) + 1) / 3) 22996 (powMod (2 ^ 46988) 64 ((2 ^ (46988 + 1) + 1) / 3) 22995 1) 451 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 23458` for the first two rises from every odd `n < 2^23446`. -/
theorem allPairs23446 : AllPairs 23446 23458 := allPairs_of_range ((((((((((((((((((((((((((((((((((((((((((((((rangeOK_sound tr23446_0).trans (rangeOK_sound tr23446_1)).trans (rangeOK_sound tr23446_2)).trans (rangeOK_sound tr23446_3)).trans (rangeOK_sound tr23446_4)).trans (rangeOK_sound tr23446_5)).trans (rangeOK_sound tr23446_6)).trans (rangeOK_sound tr23446_7)).trans (rangeOK_sound tr23446_8)).trans (rangeOK_sound tr23446_9)).trans (rangeOK_sound tr23446_10)).trans (rangeOK_sound tr23446_11)).trans (rangeOK_sound tr23446_12)).trans (rangeOK_sound tr23446_13)).trans (rangeOK_sound tr23446_14)).trans (rangeOK_sound tr23446_15)).trans (rangeOK_sound tr23446_16)).trans (rangeOK_sound tr23446_17)).trans (rangeOK_sound tr23446_18)).trans (rangeOK_sound tr23446_19)).trans (rangeOK_sound tr23446_20)).trans (rangeOK_sound tr23446_21)).trans (rangeOK_sound tr23446_22)).trans (rangeOK_sound tr23446_23)).trans (rangeOK_sound tr23446_24)).trans (rangeOK_sound tr23446_25)).trans (rangeOK_sound tr23446_26)).trans (rangeOK_sound tr23446_27)).trans (rangeOK_sound tr23446_28)).trans (rangeOK_sound tr23446_29)).trans (rangeOK_sound tr23446_30)).trans (rangeOK_sound tr23446_31)).trans (rangeOK_sound tr23446_32)).trans (rangeOK_sound tr23446_33)).trans (rangeOK_sound tr23446_34)).trans (rangeOK_sound tr23446_35)).trans (rangeOK_sound tr23446_36)).trans (rangeOK_sound tr23446_37)).trans (rangeOK_sound tr23446_38)).trans (rangeOK_sound tr23446_39)).trans (rangeOK_sound tr23446_40)).trans (rangeOK_sound tr23446_41)).trans (rangeOK_sound tr23446_42)).trans (rangeOK_sound tr23446_43)).trans (rangeOK_sound tr23446_44)).trans (rangeOK_sound tr23446_45))

end Collatz.TwoRise
