import Collatz.TwoRiseCheck

/-!
# Two-rise bounds for the chains of the `m`-cycle exclusions (kernel checks)

Generated by `research/scripts/mcycle101_certgen/gen_lean.py`. Each `AllPairs N B` is
`rangeOK` evaluated by the kernel on chunks of at most 3000 first rises
(`N` = 72, 73, 74, 75, 76, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 187, 188, 189, 190, 191, 193, 194, 195, 196, 301, 304, 306, 310, 314, 315, 483, 487, 501, 775, 799).
-/

set_option Elab.async false

namespace Collatz.TwoRise

theorem tr72_0 : rangeOK 72 84 16 240 ((2 ^ (240 + 1) + 1) / 3) 1 1 72 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 84` for the first two rises from every odd `n < 2^72`. -/
theorem allPairs72 : AllPairs 72 84 := allPairs_of_range (rangeOK_sound tr72_0)

theorem tr73_0 : rangeOK 73 84 16 242 ((2 ^ (242 + 1) + 1) / 3) 1 1 73 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 84` for the first two rises from every odd `n < 2^73`. -/
theorem allPairs73 : AllPairs 73 84 := allPairs_of_range (rangeOK_sound tr73_0)

theorem tr74_0 : rangeOK 74 84 16 244 ((2 ^ (244 + 1) + 1) / 3) 1 1 74 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 84` for the first two rises from every odd `n < 2^74`. -/
theorem allPairs74 : AllPairs 74 84 := allPairs_of_range (rangeOK_sound tr74_0)

theorem tr75_0 : rangeOK 75 84 16 246 ((2 ^ (246 + 1) + 1) / 3) 1 1 75 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 84` for the first two rises from every odd `n < 2^75`. -/
theorem allPairs75 : AllPairs 75 84 := allPairs_of_range (rangeOK_sound tr75_0)

theorem tr76_0 : rangeOK 76 84 16 248 ((2 ^ (248 + 1) + 1) / 3) 1 1 76 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 84` for the first two rises from every odd `n < 2^76`. -/
theorem allPairs76 : AllPairs 76 84 := allPairs_of_range (rangeOK_sound tr76_0)

theorem tr114_0 : rangeOK 114 120 16 324 ((2 ^ (324 + 1) + 1) / 3) 1 1 114 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 120` for the first two rises from every odd `n < 2^114`. -/
theorem allPairs114 : AllPairs 114 120 := allPairs_of_range (rangeOK_sound tr114_0)

theorem tr115_0 : rangeOK 115 120 16 326 ((2 ^ (326 + 1) + 1) / 3) 1 1 115 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 120` for the first two rises from every odd `n < 2^115`. -/
theorem allPairs115 : AllPairs 115 120 := allPairs_of_range (rangeOK_sound tr115_0)

theorem tr116_0 : rangeOK 116 120 16 328 ((2 ^ (328 + 1) + 1) / 3) 1 1 116 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 120` for the first two rises from every odd `n < 2^116`. -/
theorem allPairs116 : AllPairs 116 120 := allPairs_of_range (rangeOK_sound tr116_0)

theorem tr117_0 : rangeOK 117 124 16 330 ((2 ^ (330 + 1) + 1) / 3) 1 1 117 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 124` for the first two rises from every odd `n < 2^117`. -/
theorem allPairs117 : AllPairs 117 124 := allPairs_of_range (rangeOK_sound tr117_0)

theorem tr118_0 : rangeOK 118 124 16 332 ((2 ^ (332 + 1) + 1) / 3) 1 1 118 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 124` for the first two rises from every odd `n < 2^118`. -/
theorem allPairs118 : AllPairs 118 124 := allPairs_of_range (rangeOK_sound tr118_0)

theorem tr119_0 : rangeOK 119 124 16 334 ((2 ^ (334 + 1) + 1) / 3) 1 1 119 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 124` for the first two rises from every odd `n < 2^119`. -/
theorem allPairs119 : AllPairs 119 124 := allPairs_of_range (rangeOK_sound tr119_0)

theorem tr120_0 : rangeOK 120 125 16 336 ((2 ^ (336 + 1) + 1) / 3) 1 1 120 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 125` for the first two rises from every odd `n < 2^120`. -/
theorem allPairs120 : AllPairs 120 125 := allPairs_of_range (rangeOK_sound tr120_0)

theorem tr121_0 : rangeOK 121 127 16 338 ((2 ^ (338 + 1) + 1) / 3) 1 1 121 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 127` for the first two rises from every odd `n < 2^121`. -/
theorem allPairs121 : AllPairs 121 127 := allPairs_of_range (rangeOK_sound tr121_0)

theorem tr122_0 : rangeOK 122 128 16 340 ((2 ^ (340 + 1) + 1) / 3) 1 1 122 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 128` for the first two rises from every odd `n < 2^122`. -/
theorem allPairs122 : AllPairs 122 128 := allPairs_of_range (rangeOK_sound tr122_0)

theorem tr123_0 : rangeOK 123 128 16 342 ((2 ^ (342 + 1) + 1) / 3) 1 1 123 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 128` for the first two rises from every odd `n < 2^123`. -/
theorem allPairs123 : AllPairs 123 128 := allPairs_of_range (rangeOK_sound tr123_0)

theorem tr187_0 : rangeOK 187 194 16 470 ((2 ^ (470 + 1) + 1) / 3) 1 1 187 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 194` for the first two rises from every odd `n < 2^187`. -/
theorem allPairs187 : AllPairs 187 194 := allPairs_of_range (rangeOK_sound tr187_0)

theorem tr188_0 : rangeOK 188 196 16 472 ((2 ^ (472 + 1) + 1) / 3) 1 1 188 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 196` for the first two rises from every odd `n < 2^188`. -/
theorem allPairs188 : AllPairs 188 196 := allPairs_of_range (rangeOK_sound tr188_0)

theorem tr189_0 : rangeOK 189 196 16 474 ((2 ^ (474 + 1) + 1) / 3) 1 1 189 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 196` for the first two rises from every odd `n < 2^189`. -/
theorem allPairs189 : AllPairs 189 196 := allPairs_of_range (rangeOK_sound tr189_0)

theorem tr190_0 : rangeOK 190 196 16 476 ((2 ^ (476 + 1) + 1) / 3) 1 1 190 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 196` for the first two rises from every odd `n < 2^190`. -/
theorem allPairs190 : AllPairs 190 196 := allPairs_of_range (rangeOK_sound tr190_0)

theorem tr191_0 : rangeOK 191 196 16 478 ((2 ^ (478 + 1) + 1) / 3) 1 1 191 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 196` for the first two rises from every odd `n < 2^191`. -/
theorem allPairs191 : AllPairs 191 196 := allPairs_of_range (rangeOK_sound tr191_0)

theorem tr193_0 : rangeOK 193 197 16 482 ((2 ^ (482 + 1) + 1) / 3) 1 1 193 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 197` for the first two rises from every odd `n < 2^193`. -/
theorem allPairs193 : AllPairs 193 197 := allPairs_of_range (rangeOK_sound tr193_0)

theorem tr194_0 : rangeOK 194 199 16 484 ((2 ^ (484 + 1) + 1) / 3) 1 1 194 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 199` for the first two rises from every odd `n < 2^194`. -/
theorem allPairs194 : AllPairs 194 199 := allPairs_of_range (rangeOK_sound tr194_0)

theorem tr195_0 : rangeOK 195 200 16 486 ((2 ^ (486 + 1) + 1) / 3) 1 1 195 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 200` for the first two rises from every odd `n < 2^195`. -/
theorem allPairs195 : AllPairs 195 200 := allPairs_of_range (rangeOK_sound tr195_0)

theorem tr196_0 : rangeOK 196 206 16 488 ((2 ^ (488 + 1) + 1) / 3) 1 1 196 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 206` for the first two rises from every odd `n < 2^196`. -/
theorem allPairs196 : AllPairs 196 206 := allPairs_of_range (rangeOK_sound tr196_0)

theorem tr301_0 : rangeOK 301 308 16 698 ((2 ^ (698 + 1) + 1) / 3) 1 1 301 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 308` for the first two rises from every odd `n < 2^301`. -/
theorem allPairs301 : AllPairs 301 308 := allPairs_of_range (rangeOK_sound tr301_0)

theorem tr304_0 : rangeOK 304 310 16 704 ((2 ^ (704 + 1) + 1) / 3) 1 1 304 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 310` for the first two rises from every odd `n < 2^304`. -/
theorem allPairs304 : AllPairs 304 310 := allPairs_of_range (rangeOK_sound tr304_0)

theorem tr306_0 : rangeOK 306 313 16 708 ((2 ^ (708 + 1) + 1) / 3) 1 1 306 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 313` for the first two rises from every odd `n < 2^306`. -/
theorem allPairs306 : AllPairs 306 313 := allPairs_of_range (rangeOK_sound tr306_0)

theorem tr310_0 : rangeOK 310 318 16 716 ((2 ^ (716 + 1) + 1) / 3) 1 1 310 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 318` for the first two rises from every odd `n < 2^310`. -/
theorem allPairs310 : AllPairs 310 318 := allPairs_of_range (rangeOK_sound tr310_0)

theorem tr314_0 : rangeOK 314 321 16 724 ((2 ^ (724 + 1) + 1) / 3) 1 1 314 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 321` for the first two rises from every odd `n < 2^314`. -/
theorem allPairs314 : AllPairs 314 321 := allPairs_of_range (rangeOK_sound tr314_0)

theorem tr315_0 : rangeOK 315 322 16 726 ((2 ^ (726 + 1) + 1) / 3) 1 1 315 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 322` for the first two rises from every odd `n < 2^315`. -/
theorem allPairs315 : AllPairs 315 322 := allPairs_of_range (rangeOK_sound tr315_0)

theorem tr483_0 : rangeOK 483 491 16 1062 ((2 ^ (1062 + 1) + 1) / 3) 1 1 483 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 491` for the first two rises from every odd `n < 2^483`. -/
theorem allPairs483 : AllPairs 483 491 := allPairs_of_range (rangeOK_sound tr483_0)

theorem tr487_0 : rangeOK 487 495 16 1070 ((2 ^ (1070 + 1) + 1) / 3) 1 1 487 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 495` for the first two rises from every odd `n < 2^487`. -/
theorem allPairs487 : AllPairs 487 495 := allPairs_of_range (rangeOK_sound tr487_0)

theorem tr501_0 : rangeOK 501 512 16 1098 ((2 ^ (1098 + 1) + 1) / 3) 1 1 501 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 512` for the first two rises from every odd `n < 2^501`. -/
theorem allPairs501 : AllPairs 501 512 := allPairs_of_range (rangeOK_sound tr501_0)

theorem tr775_0 : rangeOK 775 782 16 1646 ((2 ^ (1646 + 1) + 1) / 3) 1 1 775 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 782` for the first two rises from every odd `n < 2^775`. -/
theorem allPairs775 : AllPairs 775 782 := allPairs_of_range (rangeOK_sound tr775_0)

theorem tr799_0 : rangeOK 799 805 16 1694 ((2 ^ (1694 + 1) + 1) / 3) 1 1 799 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 805` for the first two rises from every odd `n < 2^799`. -/
theorem allPairs799 : AllPairs 799 805 := allPairs_of_range (rangeOK_sound tr799_0)

end Collatz.TwoRise
