import Collatz.TwoRiseCheck

/-!
# Two-rise bounds for the chains of the `m`-cycle exclusions (kernel checks)

Generated by `research/scripts/mcycle101_certgen/gen_lean.py`. Each `AllPairs N B` is
`rangeOK` evaluated by the kernel on chunks of at most 3000 first rises
(`N` = 70, 125, 182, 293, 570, 1010, 1626, 2619, 3485, 6792, 21314).
-/

set_option Elab.async false

namespace Collatz.TwoRise

theorem tr70_0 : rangeOK 70 76 16 236 ((2 ^ (236 + 1) + 1) / 3) 1 1 70 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 76` for the first two rises from every odd `n < 2^70`. -/
theorem allPairs70 : AllPairs 70 76 := allPairs_of_range (rangeOK_sound tr70_0)

theorem tr125_0 : rangeOK 125 130 16 346 ((2 ^ (346 + 1) + 1) / 3) 1 1 125 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 130` for the first two rises from every odd `n < 2^125`. -/
theorem allPairs125 : AllPairs 125 130 := allPairs_of_range (rangeOK_sound tr125_0)

theorem tr182_0 : rangeOK 182 186 16 460 ((2 ^ (460 + 1) + 1) / 3) 1 1 182 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 186` for the first two rises from every odd `n < 2^182`. -/
theorem allPairs182 : AllPairs 182 186 := allPairs_of_range (rangeOK_sound tr182_0)

theorem tr293_0 : rangeOK 293 299 16 682 ((2 ^ (682 + 1) + 1) / 3) 1 1 293 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 299` for the first two rises from every odd `n < 2^293`. -/
theorem allPairs293 : AllPairs 293 299 := allPairs_of_range (rangeOK_sound tr293_0)

theorem tr570_0 : rangeOK 570 577 16 1236 ((2 ^ (1236 + 1) + 1) / 3) 1 1 570 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 577` for the first two rises from every odd `n < 2^570`. -/
theorem allPairs570 : AllPairs 570 577 := allPairs_of_range (rangeOK_sound tr570_0)

theorem tr1010_0 : rangeOK 1010 1018 16 2116 ((2 ^ (2116 + 1) + 1) / 3) 1 1 1010 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 1018` for the first two rises from every odd `n < 2^1010`. -/
theorem allPairs1010 : AllPairs 1010 1018 := allPairs_of_range (rangeOK_sound tr1010_0)

theorem tr1626_0 : rangeOK 1626 1634 16 3348 ((2 ^ (3348 + 1) + 1) / 3) 1 1 1626 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 1634` for the first two rises from every odd `n < 2^1626`. -/
theorem allPairs1626 : AllPairs 1626 1634 := allPairs_of_range (rangeOK_sound tr1626_0)

theorem tr2619_0 : rangeOK 2619 2629 16 5334 ((2 ^ (5334 + 1) + 1) / 3) 1 1 2619 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 2629` for the first two rises from every odd `n < 2^2619`. -/
theorem allPairs2619 : AllPairs 2619 2629 := allPairs_of_range (rangeOK_sound tr2619_0)

theorem tr3485_0 : rangeOK 3485 3494 16 7066 ((2 ^ (7066 + 1) + 1) / 3) 1 1 3000 = true := by
  decide +kernel

theorem tr3485_1 : rangeOK 3485 3494 16 7066 ((2 ^ (7066 + 1) + 1) / 3) 3001 (powMod (2 ^ 7066) 64 ((2 ^ (7066 + 1) + 1) / 3) 3000 1) 485 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 3494` for the first two rises from every odd `n < 2^3485`. -/
theorem allPairs3485 : AllPairs 3485 3494 := allPairs_of_range ((rangeOK_sound tr3485_0).trans (rangeOK_sound tr3485_1))

theorem tr6792_0 : rangeOK 6792 6806 16 13680 ((2 ^ (13680 + 1) + 1) / 3) 1 1 1766 = true := by
  decide +kernel

theorem tr6792_1 : rangeOK 6792 6806 16 13680 ((2 ^ (13680 + 1) + 1) / 3) 1767 (powMod (2 ^ 13680) 64 ((2 ^ (13680 + 1) + 1) / 3) 1766 1) 1766 = true := by
  decide +kernel

theorem tr6792_2 : rangeOK 6792 6806 16 13680 ((2 ^ (13680 + 1) + 1) / 3) 3533 (powMod (2 ^ 13680) 64 ((2 ^ (13680 + 1) + 1) / 3) 3532 1) 1766 = true := by
  decide +kernel

theorem tr6792_3 : rangeOK 6792 6806 16 13680 ((2 ^ (13680 + 1) + 1) / 3) 5299 (powMod (2 ^ 13680) 64 ((2 ^ (13680 + 1) + 1) / 3) 5298 1) 1494 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 6806` for the first two rises from every odd `n < 2^6792`. -/
theorem allPairs6792 : AllPairs 6792 6806 := allPairs_of_range ((((rangeOK_sound tr6792_0).trans (rangeOK_sound tr6792_1)).trans (rangeOK_sound tr6792_2)).trans (rangeOK_sound tr6792_3))

theorem tr21314_0 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 1 1 563 = true := by
  decide +kernel

theorem tr21314_1 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 564 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 563 1) 563 = true := by
  decide +kernel

theorem tr21314_2 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 1127 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 1126 1) 563 = true := by
  decide +kernel

theorem tr21314_3 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 1690 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 1689 1) 563 = true := by
  decide +kernel

theorem tr21314_4 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 2253 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 2252 1) 563 = true := by
  decide +kernel

theorem tr21314_5 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 2816 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 2815 1) 563 = true := by
  decide +kernel

theorem tr21314_6 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 3379 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 3378 1) 563 = true := by
  decide +kernel

theorem tr21314_7 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 3942 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 3941 1) 563 = true := by
  decide +kernel

theorem tr21314_8 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 4505 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 4504 1) 563 = true := by
  decide +kernel

theorem tr21314_9 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 5068 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 5067 1) 563 = true := by
  decide +kernel

theorem tr21314_10 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 5631 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 5630 1) 563 = true := by
  decide +kernel

theorem tr21314_11 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 6194 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 6193 1) 563 = true := by
  decide +kernel

theorem tr21314_12 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 6757 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 6756 1) 563 = true := by
  decide +kernel

theorem tr21314_13 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 7320 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 7319 1) 563 = true := by
  decide +kernel

theorem tr21314_14 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 7883 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 7882 1) 563 = true := by
  decide +kernel

theorem tr21314_15 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 8446 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 8445 1) 563 = true := by
  decide +kernel

theorem tr21314_16 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 9009 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 9008 1) 563 = true := by
  decide +kernel

theorem tr21314_17 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 9572 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 9571 1) 563 = true := by
  decide +kernel

theorem tr21314_18 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 10135 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 10134 1) 563 = true := by
  decide +kernel

theorem tr21314_19 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 10698 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 10697 1) 563 = true := by
  decide +kernel

theorem tr21314_20 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 11261 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 11260 1) 563 = true := by
  decide +kernel

theorem tr21314_21 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 11824 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 11823 1) 563 = true := by
  decide +kernel

theorem tr21314_22 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 12387 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 12386 1) 563 = true := by
  decide +kernel

theorem tr21314_23 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 12950 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 12949 1) 563 = true := by
  decide +kernel

theorem tr21314_24 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 13513 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 13512 1) 563 = true := by
  decide +kernel

theorem tr21314_25 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 14076 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 14075 1) 563 = true := by
  decide +kernel

theorem tr21314_26 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 14639 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 14638 1) 563 = true := by
  decide +kernel

theorem tr21314_27 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 15202 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 15201 1) 563 = true := by
  decide +kernel

theorem tr21314_28 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 15765 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 15764 1) 563 = true := by
  decide +kernel

theorem tr21314_29 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 16328 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 16327 1) 563 = true := by
  decide +kernel

theorem tr21314_30 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 16891 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 16890 1) 563 = true := by
  decide +kernel

theorem tr21314_31 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 17454 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 17453 1) 563 = true := by
  decide +kernel

theorem tr21314_32 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 18017 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 18016 1) 563 = true := by
  decide +kernel

theorem tr21314_33 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 18580 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 18579 1) 563 = true := by
  decide +kernel

theorem tr21314_34 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 19143 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 19142 1) 563 = true := by
  decide +kernel

theorem tr21314_35 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 19706 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 19705 1) 563 = true := by
  decide +kernel

theorem tr21314_36 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 20269 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 20268 1) 563 = true := by
  decide +kernel

theorem tr21314_37 : rangeOK 21314 21327 16 42724 ((2 ^ (42724 + 1) + 1) / 3) 20832 (powMod (2 ^ 42724) 64 ((2 ^ (42724 + 1) + 1) / 3) 20831 1) 483 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 21327` for the first two rises from every odd `n < 2^21314`. -/
theorem allPairs21314 : AllPairs 21314 21327 := allPairs_of_range ((((((((((((((((((((((((((((((((((((((rangeOK_sound tr21314_0).trans (rangeOK_sound tr21314_1)).trans (rangeOK_sound tr21314_2)).trans (rangeOK_sound tr21314_3)).trans (rangeOK_sound tr21314_4)).trans (rangeOK_sound tr21314_5)).trans (rangeOK_sound tr21314_6)).trans (rangeOK_sound tr21314_7)).trans (rangeOK_sound tr21314_8)).trans (rangeOK_sound tr21314_9)).trans (rangeOK_sound tr21314_10)).trans (rangeOK_sound tr21314_11)).trans (rangeOK_sound tr21314_12)).trans (rangeOK_sound tr21314_13)).trans (rangeOK_sound tr21314_14)).trans (rangeOK_sound tr21314_15)).trans (rangeOK_sound tr21314_16)).trans (rangeOK_sound tr21314_17)).trans (rangeOK_sound tr21314_18)).trans (rangeOK_sound tr21314_19)).trans (rangeOK_sound tr21314_20)).trans (rangeOK_sound tr21314_21)).trans (rangeOK_sound tr21314_22)).trans (rangeOK_sound tr21314_23)).trans (rangeOK_sound tr21314_24)).trans (rangeOK_sound tr21314_25)).trans (rangeOK_sound tr21314_26)).trans (rangeOK_sound tr21314_27)).trans (rangeOK_sound tr21314_28)).trans (rangeOK_sound tr21314_29)).trans (rangeOK_sound tr21314_30)).trans (rangeOK_sound tr21314_31)).trans (rangeOK_sound tr21314_32)).trans (rangeOK_sound tr21314_33)).trans (rangeOK_sound tr21314_34)).trans (rangeOK_sound tr21314_35)).trans (rangeOK_sound tr21314_36)).trans (rangeOK_sound tr21314_37))

end Collatz.TwoRise
