import Collatz.MCycleSteps
import Collatz.MCycleTwoRiseLo
import Collatz.MCycleTwoRiseHi1
import Collatz.MCycleTwoRiseHi2
import Collatz.MCycleTwoRiseHi3
import Collatz.MCycleTwoRiseHi4
import Collatz.MCycleTwoRiseHi5
import Collatz.MCycleTwoRiseHi6

/-!
# Two-rise bounds for the chains: the grid `gridHi` (97 values of `N`)

Generated by `research/scripts/mcycle101_certgen/gen_lean.py`.
-/

namespace Collatz

/-- The two-rise bounds `(N, B)` (increasing `N`). -/
def gridHi : List (ℕ × ℕ) := [(70, 76),
    (72, 84),
    (73, 84),
    (74, 84),
    (75, 84),
    (76, 84),
    (77, 84),
    (85, 91),
    (94, 99),
    (103, 107),
    (113, 120),
    (114, 120),
    (115, 120),
    (116, 120),
    (117, 124),
    (118, 124),
    (119, 124),
    (120, 125),
    (121, 127),
    (122, 128),
    (123, 128),
    (125, 130),
    (137, 143),
    (151, 158),
    (166, 174),
    (182, 186),
    (187, 194),
    (188, 196),
    (189, 196),
    (190, 196),
    (191, 196),
    (193, 197),
    (194, 199),
    (195, 200),
    (196, 206),
    (200, 206),
    (220, 224),
    (242, 249),
    (266, 274),
    (293, 299),
    (301, 308),
    (304, 310),
    (306, 313),
    (310, 318),
    (314, 321),
    (315, 322),
    (322, 328),
    (354, 362),
    (390, 398),
    (429, 435),
    (471, 478),
    (483, 491),
    (487, 495),
    (501, 512),
    (519, 526),
    (570, 577),
    (627, 634),
    (690, 699),
    (759, 766),
    (775, 782),
    (799, 805),
    (835, 842),
    (918, 929),
    (1010, 1018),
    (1111, 1120),
    (1222, 1231),
    (1344, 1352),
    (1478, 1486),
    (1626, 1634),
    (1789, 1798),
    (1968, 1976),
    (2164, 2174),
    (2381, 2392),
    (2619, 2629),
    (2881, 2895),
    (3169, 3178),
    (3485, 3494),
    (3834, 3843),
    (4217, 4228),
    (4639, 4651),
    (5103, 5113),
    (5613, 5626),
    (6174, 6183),
    (6792, 6806),
    (7471, 7483),
    (8218, 8231),
    (9040, 9054),
    (9944, 9959),
    (10938, 10952),
    (12032, 12043),
    (13235, 13248),
    (14558, 14573),
    (16014, 16028),
    (17615, 17627),
    (19377, 19395),
    (21314, 21327),
    (23446, 23458)]

theorem gridHi_cons {e₀ : ℕ × ℕ} {l : List (ℕ × ℕ)} (h₀ : TwoRiseBound e₀.1 e₀.2)
    (hl : ∀ e ∈ l, TwoRiseBound e.1 e.2) : ∀ e ∈ e₀ :: l, TwoRiseBound e.1 e.2 := by
  intro e he
  rcases List.mem_cons.mp he with h | h
  · rw [h]; exact h₀
  · exact hl e h

theorem gridHi_nil : ∀ e ∈ ([] : List (ℕ × ℕ)), TwoRiseBound e.1 e.2 := by
  intro e he
  cases he

theorem gridHi_ok : ∀ e ∈ gridHi, TwoRiseBound e.1 e.2 := by
  unfold gridHi
  exact gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs70) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs72) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs73) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs74) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs75) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs76) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs77) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs85) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs94) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs103) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs113) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs114) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs115) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs116) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs117) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs118) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs119) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs120) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs121) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs122) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs123) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs125) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs137) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs151) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs166) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs182) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs187) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs188) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs189) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs190) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs191) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs193) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs194) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs195) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs196) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs200) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs220) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs242) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs266) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs293) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs301) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs304) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs306) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs310) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs314) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs315) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs322) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs354) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs390) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs429) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs471) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs483) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs487) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs501) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs519) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs570) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs627) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs690) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs759) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs775) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs799) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs835) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs918) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs1010) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs1111) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs1222) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs1344) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs1478) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs1626) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs1789) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs1968) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs2164) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs2381) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs2619) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs2881) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs3169) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs3485) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs3834) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs4217) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs4639) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs5103) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs5613) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs6174) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs6792) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs7471) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs8218) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs9040) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs9944) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs10938) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs12032) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs13235) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs14558) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs16014) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs17615) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs19377) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs21314) <|
    gridHi_cons (twoRiseBound_of_allPairs TwoRise.allPairs23446) <|
    gridHi_nil

end Collatz
