import Collatz.TwoRiseCheck

/-!
# Two-rise bounds for the chains of the `m`-cycle exclusions (kernel checks)

Generated by `research/scripts/mcycle101_certgen/gen_lean.py`. Each `AllPairs N B` is
`rangeOK` evaluated by the kernel on chunks of at most 3000 first rises
(`N` = 113, 166, 266, 627, 690, 1344, 2381, 3834, 5103, 9944, 19377).
-/

set_option Elab.async false

namespace Collatz.TwoRise

theorem tr113_0 : rangeOK 113 120 16 322 ((2 ^ (322 + 1) + 1) / 3) 1 1 113 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 120` for the first two rises from every odd `n < 2^113`. -/
theorem allPairs113 : AllPairs 113 120 := allPairs_of_range (rangeOK_sound tr113_0)

theorem tr166_0 : rangeOK 166 174 16 428 ((2 ^ (428 + 1) + 1) / 3) 1 1 166 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 174` for the first two rises from every odd `n < 2^166`. -/
theorem allPairs166 : AllPairs 166 174 := allPairs_of_range (rangeOK_sound tr166_0)

theorem tr266_0 : rangeOK 266 274 16 628 ((2 ^ (628 + 1) + 1) / 3) 1 1 266 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 274` for the first two rises from every odd `n < 2^266`. -/
theorem allPairs266 : AllPairs 266 274 := allPairs_of_range (rangeOK_sound tr266_0)

theorem tr627_0 : rangeOK 627 634 16 1350 ((2 ^ (1350 + 1) + 1) / 3) 1 1 627 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 634` for the first two rises from every odd `n < 2^627`. -/
theorem allPairs627 : AllPairs 627 634 := allPairs_of_range (rangeOK_sound tr627_0)

theorem tr690_0 : rangeOK 690 699 16 1476 ((2 ^ (1476 + 1) + 1) / 3) 1 1 690 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 699` for the first two rises from every odd `n < 2^690`. -/
theorem allPairs690 : AllPairs 690 699 := allPairs_of_range (rangeOK_sound tr690_0)

theorem tr1344_0 : rangeOK 1344 1352 16 2784 ((2 ^ (2784 + 1) + 1) / 3) 1 1 1344 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 1352` for the first two rises from every odd `n < 2^1344`. -/
theorem allPairs1344 : AllPairs 1344 1352 := allPairs_of_range (rangeOK_sound tr1344_0)

theorem tr2381_0 : rangeOK 2381 2392 16 4858 ((2 ^ (4858 + 1) + 1) / 3) 1 1 2381 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 2392` for the first two rises from every odd `n < 2^2381`. -/
theorem allPairs2381 : AllPairs 2381 2392 := allPairs_of_range (rangeOK_sound tr2381_0)

theorem tr3834_0 : rangeOK 3834 3843 16 7764 ((2 ^ (7764 + 1) + 1) / 3) 1 1 3000 = true := by
  decide +kernel

theorem tr3834_1 : rangeOK 3834 3843 16 7764 ((2 ^ (7764 + 1) + 1) / 3) 3001 (powMod (2 ^ 7764) 64 ((2 ^ (7764 + 1) + 1) / 3) 3000 1) 834 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 3843` for the first two rises from every odd `n < 2^3834`. -/
theorem allPairs3834 : AllPairs 3834 3843 := allPairs_of_range ((rangeOK_sound tr3834_0).trans (rangeOK_sound tr3834_1))

theorem tr5103_0 : rangeOK 5103 5113 16 10302 ((2 ^ (10302 + 1) + 1) / 3) 1 1 2351 = true := by
  decide +kernel

theorem tr5103_1 : rangeOK 5103 5113 16 10302 ((2 ^ (10302 + 1) + 1) / 3) 2352 (powMod (2 ^ 10302) 64 ((2 ^ (10302 + 1) + 1) / 3) 2351 1) 2351 = true := by
  decide +kernel

theorem tr5103_2 : rangeOK 5103 5113 16 10302 ((2 ^ (10302 + 1) + 1) / 3) 4703 (powMod (2 ^ 10302) 64 ((2 ^ (10302 + 1) + 1) / 3) 4702 1) 401 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 5113` for the first two rises from every odd `n < 2^5103`. -/
theorem allPairs5103 : AllPairs 5103 5113 := allPairs_of_range (((rangeOK_sound tr5103_0).trans (rangeOK_sound tr5103_1)).trans (rangeOK_sound tr5103_2))

theorem tr9944_0 : rangeOK 9944 9959 16 19984 ((2 ^ (19984 + 1) + 1) / 3) 1 1 1206 = true := by
  decide +kernel

theorem tr9944_1 : rangeOK 9944 9959 16 19984 ((2 ^ (19984 + 1) + 1) / 3) 1207 (powMod (2 ^ 19984) 64 ((2 ^ (19984 + 1) + 1) / 3) 1206 1) 1206 = true := by
  decide +kernel

theorem tr9944_2 : rangeOK 9944 9959 16 19984 ((2 ^ (19984 + 1) + 1) / 3) 2413 (powMod (2 ^ 19984) 64 ((2 ^ (19984 + 1) + 1) / 3) 2412 1) 1206 = true := by
  decide +kernel

theorem tr9944_3 : rangeOK 9944 9959 16 19984 ((2 ^ (19984 + 1) + 1) / 3) 3619 (powMod (2 ^ 19984) 64 ((2 ^ (19984 + 1) + 1) / 3) 3618 1) 1206 = true := by
  decide +kernel

theorem tr9944_4 : rangeOK 9944 9959 16 19984 ((2 ^ (19984 + 1) + 1) / 3) 4825 (powMod (2 ^ 19984) 64 ((2 ^ (19984 + 1) + 1) / 3) 4824 1) 1206 = true := by
  decide +kernel

theorem tr9944_5 : rangeOK 9944 9959 16 19984 ((2 ^ (19984 + 1) + 1) / 3) 6031 (powMod (2 ^ 19984) 64 ((2 ^ (19984 + 1) + 1) / 3) 6030 1) 1206 = true := by
  decide +kernel

theorem tr9944_6 : rangeOK 9944 9959 16 19984 ((2 ^ (19984 + 1) + 1) / 3) 7237 (powMod (2 ^ 19984) 64 ((2 ^ (19984 + 1) + 1) / 3) 7236 1) 1206 = true := by
  decide +kernel

theorem tr9944_7 : rangeOK 9944 9959 16 19984 ((2 ^ (19984 + 1) + 1) / 3) 8443 (powMod (2 ^ 19984) 64 ((2 ^ (19984 + 1) + 1) / 3) 8442 1) 1206 = true := by
  decide +kernel

theorem tr9944_8 : rangeOK 9944 9959 16 19984 ((2 ^ (19984 + 1) + 1) / 3) 9649 (powMod (2 ^ 19984) 64 ((2 ^ (19984 + 1) + 1) / 3) 9648 1) 296 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 9959` for the first two rises from every odd `n < 2^9944`. -/
theorem allPairs9944 : AllPairs 9944 9959 := allPairs_of_range (((((((((rangeOK_sound tr9944_0).trans (rangeOK_sound tr9944_1)).trans (rangeOK_sound tr9944_2)).trans (rangeOK_sound tr9944_3)).trans (rangeOK_sound tr9944_4)).trans (rangeOK_sound tr9944_5)).trans (rangeOK_sound tr9944_6)).trans (rangeOK_sound tr9944_7)).trans (rangeOK_sound tr9944_8))

theorem tr19377_0 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 1 1 619 = true := by
  decide +kernel

theorem tr19377_1 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 620 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 619 1) 619 = true := by
  decide +kernel

theorem tr19377_2 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 1239 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 1238 1) 619 = true := by
  decide +kernel

theorem tr19377_3 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 1858 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 1857 1) 619 = true := by
  decide +kernel

theorem tr19377_4 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 2477 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 2476 1) 619 = true := by
  decide +kernel

theorem tr19377_5 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 3096 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 3095 1) 619 = true := by
  decide +kernel

theorem tr19377_6 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 3715 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 3714 1) 619 = true := by
  decide +kernel

theorem tr19377_7 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 4334 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 4333 1) 619 = true := by
  decide +kernel

theorem tr19377_8 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 4953 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 4952 1) 619 = true := by
  decide +kernel

theorem tr19377_9 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 5572 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 5571 1) 619 = true := by
  decide +kernel

theorem tr19377_10 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 6191 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 6190 1) 619 = true := by
  decide +kernel

theorem tr19377_11 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 6810 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 6809 1) 619 = true := by
  decide +kernel

theorem tr19377_12 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 7429 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 7428 1) 619 = true := by
  decide +kernel

theorem tr19377_13 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 8048 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 8047 1) 619 = true := by
  decide +kernel

theorem tr19377_14 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 8667 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 8666 1) 619 = true := by
  decide +kernel

theorem tr19377_15 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 9286 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 9285 1) 619 = true := by
  decide +kernel

theorem tr19377_16 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 9905 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 9904 1) 619 = true := by
  decide +kernel

theorem tr19377_17 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 10524 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 10523 1) 619 = true := by
  decide +kernel

theorem tr19377_18 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 11143 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 11142 1) 619 = true := by
  decide +kernel

theorem tr19377_19 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 11762 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 11761 1) 619 = true := by
  decide +kernel

theorem tr19377_20 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 12381 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 12380 1) 619 = true := by
  decide +kernel

theorem tr19377_21 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 13000 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 12999 1) 619 = true := by
  decide +kernel

theorem tr19377_22 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 13619 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 13618 1) 619 = true := by
  decide +kernel

theorem tr19377_23 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 14238 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 14237 1) 619 = true := by
  decide +kernel

theorem tr19377_24 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 14857 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 14856 1) 619 = true := by
  decide +kernel

theorem tr19377_25 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 15476 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 15475 1) 619 = true := by
  decide +kernel

theorem tr19377_26 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 16095 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 16094 1) 619 = true := by
  decide +kernel

theorem tr19377_27 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 16714 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 16713 1) 619 = true := by
  decide +kernel

theorem tr19377_28 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 17333 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 17332 1) 619 = true := by
  decide +kernel

theorem tr19377_29 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 17952 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 17951 1) 619 = true := by
  decide +kernel

theorem tr19377_30 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 18571 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 18570 1) 619 = true := by
  decide +kernel

theorem tr19377_31 : rangeOK 19377 19395 16 38850 ((2 ^ (38850 + 1) + 1) / 3) 19190 (powMod (2 ^ 38850) 64 ((2 ^ (38850 + 1) + 1) / 3) 19189 1) 188 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 19395` for the first two rises from every odd `n < 2^19377`. -/
theorem allPairs19377 : AllPairs 19377 19395 := allPairs_of_range ((((((((((((((((((((((((((((((((rangeOK_sound tr19377_0).trans (rangeOK_sound tr19377_1)).trans (rangeOK_sound tr19377_2)).trans (rangeOK_sound tr19377_3)).trans (rangeOK_sound tr19377_4)).trans (rangeOK_sound tr19377_5)).trans (rangeOK_sound tr19377_6)).trans (rangeOK_sound tr19377_7)).trans (rangeOK_sound tr19377_8)).trans (rangeOK_sound tr19377_9)).trans (rangeOK_sound tr19377_10)).trans (rangeOK_sound tr19377_11)).trans (rangeOK_sound tr19377_12)).trans (rangeOK_sound tr19377_13)).trans (rangeOK_sound tr19377_14)).trans (rangeOK_sound tr19377_15)).trans (rangeOK_sound tr19377_16)).trans (rangeOK_sound tr19377_17)).trans (rangeOK_sound tr19377_18)).trans (rangeOK_sound tr19377_19)).trans (rangeOK_sound tr19377_20)).trans (rangeOK_sound tr19377_21)).trans (rangeOK_sound tr19377_22)).trans (rangeOK_sound tr19377_23)).trans (rangeOK_sound tr19377_24)).trans (rangeOK_sound tr19377_25)).trans (rangeOK_sound tr19377_26)).trans (rangeOK_sound tr19377_27)).trans (rangeOK_sound tr19377_28)).trans (rangeOK_sound tr19377_29)).trans (rangeOK_sound tr19377_30)).trans (rangeOK_sound tr19377_31))

end Collatz.TwoRise
