import Collatz.TwoRiseCheck

/-!
# Two-rise bounds for the chains of the `m`-cycle exclusions (kernel checks)

Generated by `research/scripts/mcycle101_certgen/gen_lean.py`. Each `AllPairs N B` is
`rangeOK` evaluated by the kernel on chunks of at most 3000 first rises
(`N` = 85, 137, 242, 390, 429, 835, 1478, 2164, 2881, 4639, 7471, 10938, 17615).
-/

set_option Elab.async false

namespace Collatz.TwoRise

theorem tr85_0 : rangeOK 85 91 16 266 ((2 ^ (266 + 1) + 1) / 3) 1 1 85 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 91` for the first two rises from every odd `n < 2^85`. -/
theorem allPairs85 : AllPairs 85 91 := allPairs_of_range (rangeOK_sound tr85_0)

theorem tr137_0 : rangeOK 137 143 16 370 ((2 ^ (370 + 1) + 1) / 3) 1 1 137 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 143` for the first two rises from every odd `n < 2^137`. -/
theorem allPairs137 : AllPairs 137 143 := allPairs_of_range (rangeOK_sound tr137_0)

theorem tr242_0 : rangeOK 242 249 16 580 ((2 ^ (580 + 1) + 1) / 3) 1 1 242 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 249` for the first two rises from every odd `n < 2^242`. -/
theorem allPairs242 : AllPairs 242 249 := allPairs_of_range (rangeOK_sound tr242_0)

theorem tr390_0 : rangeOK 390 398 16 876 ((2 ^ (876 + 1) + 1) / 3) 1 1 390 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 398` for the first two rises from every odd `n < 2^390`. -/
theorem allPairs390 : AllPairs 390 398 := allPairs_of_range (rangeOK_sound tr390_0)

theorem tr429_0 : rangeOK 429 435 16 954 ((2 ^ (954 + 1) + 1) / 3) 1 1 429 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 435` for the first two rises from every odd `n < 2^429`. -/
theorem allPairs429 : AllPairs 429 435 := allPairs_of_range (rangeOK_sound tr429_0)

theorem tr835_0 : rangeOK 835 842 16 1766 ((2 ^ (1766 + 1) + 1) / 3) 1 1 835 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 842` for the first two rises from every odd `n < 2^835`. -/
theorem allPairs835 : AllPairs 835 842 := allPairs_of_range (rangeOK_sound tr835_0)

theorem tr1478_0 : rangeOK 1478 1486 16 3052 ((2 ^ (3052 + 1) + 1) / 3) 1 1 1478 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 1486` for the first two rises from every odd `n < 2^1478`. -/
theorem allPairs1478 : AllPairs 1478 1486 := allPairs_of_range (rangeOK_sound tr1478_0)

theorem tr2164_0 : rangeOK 2164 2174 16 4424 ((2 ^ (4424 + 1) + 1) / 3) 1 1 2164 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 2174` for the first two rises from every odd `n < 2^2164`. -/
theorem allPairs2164 : AllPairs 2164 2174 := allPairs_of_range (rangeOK_sound tr2164_0)

theorem tr2881_0 : rangeOK 2881 2895 16 5858 ((2 ^ (5858 + 1) + 1) / 3) 1 1 2881 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 2895` for the first two rises from every odd `n < 2^2881`. -/
theorem allPairs2881 : AllPairs 2881 2895 := allPairs_of_range (rangeOK_sound tr2881_0)

theorem tr4639_0 : rangeOK 4639 4651 16 9374 ((2 ^ (9374 + 1) + 1) / 3) 1 1 2586 = true := by
  decide +kernel

theorem tr4639_1 : rangeOK 4639 4651 16 9374 ((2 ^ (9374 + 1) + 1) / 3) 2587 (powMod (2 ^ 9374) 64 ((2 ^ (9374 + 1) + 1) / 3) 2586 1) 2053 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 4651` for the first two rises from every odd `n < 2^4639`. -/
theorem allPairs4639 : AllPairs 4639 4651 := allPairs_of_range ((rangeOK_sound tr4639_0).trans (rangeOK_sound tr4639_1))

theorem tr7471_0 : rangeOK 7471 7483 16 15038 ((2 ^ (15038 + 1) + 1) / 3) 1 1 1606 = true := by
  decide +kernel

theorem tr7471_1 : rangeOK 7471 7483 16 15038 ((2 ^ (15038 + 1) + 1) / 3) 1607 (powMod (2 ^ 15038) 64 ((2 ^ (15038 + 1) + 1) / 3) 1606 1) 1606 = true := by
  decide +kernel

theorem tr7471_2 : rangeOK 7471 7483 16 15038 ((2 ^ (15038 + 1) + 1) / 3) 3213 (powMod (2 ^ 15038) 64 ((2 ^ (15038 + 1) + 1) / 3) 3212 1) 1606 = true := by
  decide +kernel

theorem tr7471_3 : rangeOK 7471 7483 16 15038 ((2 ^ (15038 + 1) + 1) / 3) 4819 (powMod (2 ^ 15038) 64 ((2 ^ (15038 + 1) + 1) / 3) 4818 1) 1606 = true := by
  decide +kernel

theorem tr7471_4 : rangeOK 7471 7483 16 15038 ((2 ^ (15038 + 1) + 1) / 3) 6425 (powMod (2 ^ 15038) 64 ((2 ^ (15038 + 1) + 1) / 3) 6424 1) 1047 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 7483` for the first two rises from every odd `n < 2^7471`. -/
theorem allPairs7471 : AllPairs 7471 7483 := allPairs_of_range (((((rangeOK_sound tr7471_0).trans (rangeOK_sound tr7471_1)).trans (rangeOK_sound tr7471_2)).trans (rangeOK_sound tr7471_3)).trans (rangeOK_sound tr7471_4))

theorem tr10938_0 : rangeOK 10938 10952 16 21972 ((2 ^ (21972 + 1) + 1) / 3) 1 1 1097 = true := by
  decide +kernel

theorem tr10938_1 : rangeOK 10938 10952 16 21972 ((2 ^ (21972 + 1) + 1) / 3) 1098 (powMod (2 ^ 21972) 64 ((2 ^ (21972 + 1) + 1) / 3) 1097 1) 1097 = true := by
  decide +kernel

theorem tr10938_2 : rangeOK 10938 10952 16 21972 ((2 ^ (21972 + 1) + 1) / 3) 2195 (powMod (2 ^ 21972) 64 ((2 ^ (21972 + 1) + 1) / 3) 2194 1) 1097 = true := by
  decide +kernel

theorem tr10938_3 : rangeOK 10938 10952 16 21972 ((2 ^ (21972 + 1) + 1) / 3) 3292 (powMod (2 ^ 21972) 64 ((2 ^ (21972 + 1) + 1) / 3) 3291 1) 1097 = true := by
  decide +kernel

theorem tr10938_4 : rangeOK 10938 10952 16 21972 ((2 ^ (21972 + 1) + 1) / 3) 4389 (powMod (2 ^ 21972) 64 ((2 ^ (21972 + 1) + 1) / 3) 4388 1) 1097 = true := by
  decide +kernel

theorem tr10938_5 : rangeOK 10938 10952 16 21972 ((2 ^ (21972 + 1) + 1) / 3) 5486 (powMod (2 ^ 21972) 64 ((2 ^ (21972 + 1) + 1) / 3) 5485 1) 1097 = true := by
  decide +kernel

theorem tr10938_6 : rangeOK 10938 10952 16 21972 ((2 ^ (21972 + 1) + 1) / 3) 6583 (powMod (2 ^ 21972) 64 ((2 ^ (21972 + 1) + 1) / 3) 6582 1) 1097 = true := by
  decide +kernel

theorem tr10938_7 : rangeOK 10938 10952 16 21972 ((2 ^ (21972 + 1) + 1) / 3) 7680 (powMod (2 ^ 21972) 64 ((2 ^ (21972 + 1) + 1) / 3) 7679 1) 1097 = true := by
  decide +kernel

theorem tr10938_8 : rangeOK 10938 10952 16 21972 ((2 ^ (21972 + 1) + 1) / 3) 8777 (powMod (2 ^ 21972) 64 ((2 ^ (21972 + 1) + 1) / 3) 8776 1) 1097 = true := by
  decide +kernel

theorem tr10938_9 : rangeOK 10938 10952 16 21972 ((2 ^ (21972 + 1) + 1) / 3) 9874 (powMod (2 ^ 21972) 64 ((2 ^ (21972 + 1) + 1) / 3) 9873 1) 1065 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 10952` for the first two rises from every odd `n < 2^10938`. -/
theorem allPairs10938 : AllPairs 10938 10952 := allPairs_of_range ((((((((((rangeOK_sound tr10938_0).trans (rangeOK_sound tr10938_1)).trans (rangeOK_sound tr10938_2)).trans (rangeOK_sound tr10938_3)).trans (rangeOK_sound tr10938_4)).trans (rangeOK_sound tr10938_5)).trans (rangeOK_sound tr10938_6)).trans (rangeOK_sound tr10938_7)).trans (rangeOK_sound tr10938_8)).trans (rangeOK_sound tr10938_9))

theorem tr17615_0 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 1 1 681 = true := by
  decide +kernel

theorem tr17615_1 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 682 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 681 1) 681 = true := by
  decide +kernel

theorem tr17615_2 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 1363 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 1362 1) 681 = true := by
  decide +kernel

theorem tr17615_3 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 2044 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 2043 1) 681 = true := by
  decide +kernel

theorem tr17615_4 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 2725 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 2724 1) 681 = true := by
  decide +kernel

theorem tr17615_5 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 3406 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 3405 1) 681 = true := by
  decide +kernel

theorem tr17615_6 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 4087 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 4086 1) 681 = true := by
  decide +kernel

theorem tr17615_7 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 4768 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 4767 1) 681 = true := by
  decide +kernel

theorem tr17615_8 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 5449 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 5448 1) 681 = true := by
  decide +kernel

theorem tr17615_9 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 6130 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 6129 1) 681 = true := by
  decide +kernel

theorem tr17615_10 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 6811 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 6810 1) 681 = true := by
  decide +kernel

theorem tr17615_11 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 7492 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 7491 1) 681 = true := by
  decide +kernel

theorem tr17615_12 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 8173 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 8172 1) 681 = true := by
  decide +kernel

theorem tr17615_13 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 8854 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 8853 1) 681 = true := by
  decide +kernel

theorem tr17615_14 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 9535 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 9534 1) 681 = true := by
  decide +kernel

theorem tr17615_15 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 10216 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 10215 1) 681 = true := by
  decide +kernel

theorem tr17615_16 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 10897 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 10896 1) 681 = true := by
  decide +kernel

theorem tr17615_17 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 11578 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 11577 1) 681 = true := by
  decide +kernel

theorem tr17615_18 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 12259 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 12258 1) 681 = true := by
  decide +kernel

theorem tr17615_19 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 12940 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 12939 1) 681 = true := by
  decide +kernel

theorem tr17615_20 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 13621 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 13620 1) 681 = true := by
  decide +kernel

theorem tr17615_21 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 14302 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 14301 1) 681 = true := by
  decide +kernel

theorem tr17615_22 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 14983 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 14982 1) 681 = true := by
  decide +kernel

theorem tr17615_23 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 15664 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 15663 1) 681 = true := by
  decide +kernel

theorem tr17615_24 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 16345 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 16344 1) 681 = true := by
  decide +kernel

theorem tr17615_25 : rangeOK 17615 17627 16 35326 ((2 ^ (35326 + 1) + 1) / 3) 17026 (powMod (2 ^ 35326) 64 ((2 ^ (35326 + 1) + 1) / 3) 17025 1) 590 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 17627` for the first two rises from every odd `n < 2^17615`. -/
theorem allPairs17615 : AllPairs 17615 17627 := allPairs_of_range ((((((((((((((((((((((((((rangeOK_sound tr17615_0).trans (rangeOK_sound tr17615_1)).trans (rangeOK_sound tr17615_2)).trans (rangeOK_sound tr17615_3)).trans (rangeOK_sound tr17615_4)).trans (rangeOK_sound tr17615_5)).trans (rangeOK_sound tr17615_6)).trans (rangeOK_sound tr17615_7)).trans (rangeOK_sound tr17615_8)).trans (rangeOK_sound tr17615_9)).trans (rangeOK_sound tr17615_10)).trans (rangeOK_sound tr17615_11)).trans (rangeOK_sound tr17615_12)).trans (rangeOK_sound tr17615_13)).trans (rangeOK_sound tr17615_14)).trans (rangeOK_sound tr17615_15)).trans (rangeOK_sound tr17615_16)).trans (rangeOK_sound tr17615_17)).trans (rangeOK_sound tr17615_18)).trans (rangeOK_sound tr17615_19)).trans (rangeOK_sound tr17615_20)).trans (rangeOK_sound tr17615_21)).trans (rangeOK_sound tr17615_22)).trans (rangeOK_sound tr17615_23)).trans (rangeOK_sound tr17615_24)).trans (rangeOK_sound tr17615_25))

end Collatz.TwoRise
