import Collatz.TwoRiseCheck

/-!
# Two-rise bounds for the chains of the `m`-cycle exclusions (kernel checks)

Generated by `research/scripts/mcycle101_certgen/gen_lean.py`. Each `AllPairs N B` is
`rangeOK` evaluated by the kernel on chunks of at most 3000 first rises
(`N` = 94, 151, 220, 354, 471, 918, 1222, 1968, 3169, 6174, 8218, 12032, 16014).
-/

set_option Elab.async false

namespace Collatz.TwoRise

theorem tr94_0 : rangeOK 94 99 16 284 ((2 ^ (284 + 1) + 1) / 3) 1 1 94 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 99` for the first two rises from every odd `n < 2^94`. -/
theorem allPairs94 : AllPairs 94 99 := allPairs_of_range (rangeOK_sound tr94_0)

theorem tr151_0 : rangeOK 151 158 16 398 ((2 ^ (398 + 1) + 1) / 3) 1 1 151 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 158` for the first two rises from every odd `n < 2^151`. -/
theorem allPairs151 : AllPairs 151 158 := allPairs_of_range (rangeOK_sound tr151_0)

theorem tr220_0 : rangeOK 220 224 16 536 ((2 ^ (536 + 1) + 1) / 3) 1 1 220 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 224` for the first two rises from every odd `n < 2^220`. -/
theorem allPairs220 : AllPairs 220 224 := allPairs_of_range (rangeOK_sound tr220_0)

theorem tr354_0 : rangeOK 354 362 16 804 ((2 ^ (804 + 1) + 1) / 3) 1 1 354 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 362` for the first two rises from every odd `n < 2^354`. -/
theorem allPairs354 : AllPairs 354 362 := allPairs_of_range (rangeOK_sound tr354_0)

theorem tr471_0 : rangeOK 471 478 16 1038 ((2 ^ (1038 + 1) + 1) / 3) 1 1 471 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 478` for the first two rises from every odd `n < 2^471`. -/
theorem allPairs471 : AllPairs 471 478 := allPairs_of_range (rangeOK_sound tr471_0)

theorem tr918_0 : rangeOK 918 929 16 1932 ((2 ^ (1932 + 1) + 1) / 3) 1 1 918 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 929` for the first two rises from every odd `n < 2^918`. -/
theorem allPairs918 : AllPairs 918 929 := allPairs_of_range (rangeOK_sound tr918_0)

theorem tr1222_0 : rangeOK 1222 1231 16 2540 ((2 ^ (2540 + 1) + 1) / 3) 1 1 1222 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 1231` for the first two rises from every odd `n < 2^1222`. -/
theorem allPairs1222 : AllPairs 1222 1231 := allPairs_of_range (rangeOK_sound tr1222_0)

theorem tr1968_0 : rangeOK 1968 1976 16 4032 ((2 ^ (4032 + 1) + 1) / 3) 1 1 1968 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 1976` for the first two rises from every odd `n < 2^1968`. -/
theorem allPairs1968 : AllPairs 1968 1976 := allPairs_of_range (rangeOK_sound tr1968_0)

theorem tr3169_0 : rangeOK 3169 3178 16 6434 ((2 ^ (6434 + 1) + 1) / 3) 1 1 3000 = true := by
  decide +kernel

theorem tr3169_1 : rangeOK 3169 3178 16 6434 ((2 ^ (6434 + 1) + 1) / 3) 3001 (powMod (2 ^ 6434) 64 ((2 ^ (6434 + 1) + 1) / 3) 3000 1) 169 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 3178` for the first two rises from every odd `n < 2^3169`. -/
theorem allPairs3169 : AllPairs 3169 3178 := allPairs_of_range ((rangeOK_sound tr3169_0).trans (rangeOK_sound tr3169_1))

theorem tr6174_0 : rangeOK 6174 6183 16 12444 ((2 ^ (12444 + 1) + 1) / 3) 1 1 1943 = true := by
  decide +kernel

theorem tr6174_1 : rangeOK 6174 6183 16 12444 ((2 ^ (12444 + 1) + 1) / 3) 1944 (powMod (2 ^ 12444) 64 ((2 ^ (12444 + 1) + 1) / 3) 1943 1) 1943 = true := by
  decide +kernel

theorem tr6174_2 : rangeOK 6174 6183 16 12444 ((2 ^ (12444 + 1) + 1) / 3) 3887 (powMod (2 ^ 12444) 64 ((2 ^ (12444 + 1) + 1) / 3) 3886 1) 1943 = true := by
  decide +kernel

theorem tr6174_3 : rangeOK 6174 6183 16 12444 ((2 ^ (12444 + 1) + 1) / 3) 5830 (powMod (2 ^ 12444) 64 ((2 ^ (12444 + 1) + 1) / 3) 5829 1) 345 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 6183` for the first two rises from every odd `n < 2^6174`. -/
theorem allPairs6174 : AllPairs 6174 6183 := allPairs_of_range ((((rangeOK_sound tr6174_0).trans (rangeOK_sound tr6174_1)).trans (rangeOK_sound tr6174_2)).trans (rangeOK_sound tr6174_3))

theorem tr8218_0 : rangeOK 8218 8231 16 16532 ((2 ^ (16532 + 1) + 1) / 3) 1 1 1460 = true := by
  decide +kernel

theorem tr8218_1 : rangeOK 8218 8231 16 16532 ((2 ^ (16532 + 1) + 1) / 3) 1461 (powMod (2 ^ 16532) 64 ((2 ^ (16532 + 1) + 1) / 3) 1460 1) 1460 = true := by
  decide +kernel

theorem tr8218_2 : rangeOK 8218 8231 16 16532 ((2 ^ (16532 + 1) + 1) / 3) 2921 (powMod (2 ^ 16532) 64 ((2 ^ (16532 + 1) + 1) / 3) 2920 1) 1460 = true := by
  decide +kernel

theorem tr8218_3 : rangeOK 8218 8231 16 16532 ((2 ^ (16532 + 1) + 1) / 3) 4381 (powMod (2 ^ 16532) 64 ((2 ^ (16532 + 1) + 1) / 3) 4380 1) 1460 = true := by
  decide +kernel

theorem tr8218_4 : rangeOK 8218 8231 16 16532 ((2 ^ (16532 + 1) + 1) / 3) 5841 (powMod (2 ^ 16532) 64 ((2 ^ (16532 + 1) + 1) / 3) 5840 1) 1460 = true := by
  decide +kernel

theorem tr8218_5 : rangeOK 8218 8231 16 16532 ((2 ^ (16532 + 1) + 1) / 3) 7301 (powMod (2 ^ 16532) 64 ((2 ^ (16532 + 1) + 1) / 3) 7300 1) 918 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 8231` for the first two rises from every odd `n < 2^8218`. -/
theorem allPairs8218 : AllPairs 8218 8231 := allPairs_of_range ((((((rangeOK_sound tr8218_0).trans (rangeOK_sound tr8218_1)).trans (rangeOK_sound tr8218_2)).trans (rangeOK_sound tr8218_3)).trans (rangeOK_sound tr8218_4)).trans (rangeOK_sound tr8218_5))

theorem tr12032_0 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 1 1 997 = true := by
  decide +kernel

theorem tr12032_1 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 998 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 997 1) 997 = true := by
  decide +kernel

theorem tr12032_2 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 1995 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 1994 1) 997 = true := by
  decide +kernel

theorem tr12032_3 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 2992 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 2991 1) 997 = true := by
  decide +kernel

theorem tr12032_4 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 3989 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 3988 1) 997 = true := by
  decide +kernel

theorem tr12032_5 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 4986 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 4985 1) 997 = true := by
  decide +kernel

theorem tr12032_6 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 5983 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 5982 1) 997 = true := by
  decide +kernel

theorem tr12032_7 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 6980 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 6979 1) 997 = true := by
  decide +kernel

theorem tr12032_8 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 7977 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 7976 1) 997 = true := by
  decide +kernel

theorem tr12032_9 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 8974 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 8973 1) 997 = true := by
  decide +kernel

theorem tr12032_10 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 9971 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 9970 1) 997 = true := by
  decide +kernel

theorem tr12032_11 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 10968 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 10967 1) 997 = true := by
  decide +kernel

theorem tr12032_12 : rangeOK 12032 12043 16 24160 ((2 ^ (24160 + 1) + 1) / 3) 11965 (powMod (2 ^ 24160) 64 ((2 ^ (24160 + 1) + 1) / 3) 11964 1) 68 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 12043` for the first two rises from every odd `n < 2^12032`. -/
theorem allPairs12032 : AllPairs 12032 12043 := allPairs_of_range (((((((((((((rangeOK_sound tr12032_0).trans (rangeOK_sound tr12032_1)).trans (rangeOK_sound tr12032_2)).trans (rangeOK_sound tr12032_3)).trans (rangeOK_sound tr12032_4)).trans (rangeOK_sound tr12032_5)).trans (rangeOK_sound tr12032_6)).trans (rangeOK_sound tr12032_7)).trans (rangeOK_sound tr12032_8)).trans (rangeOK_sound tr12032_9)).trans (rangeOK_sound tr12032_10)).trans (rangeOK_sound tr12032_11)).trans (rangeOK_sound tr12032_12))

theorem tr16014_0 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 1 1 749 = true := by
  decide +kernel

theorem tr16014_1 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 750 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 749 1) 749 = true := by
  decide +kernel

theorem tr16014_2 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 1499 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 1498 1) 749 = true := by
  decide +kernel

theorem tr16014_3 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 2248 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 2247 1) 749 = true := by
  decide +kernel

theorem tr16014_4 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 2997 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 2996 1) 749 = true := by
  decide +kernel

theorem tr16014_5 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 3746 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 3745 1) 749 = true := by
  decide +kernel

theorem tr16014_6 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 4495 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 4494 1) 749 = true := by
  decide +kernel

theorem tr16014_7 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 5244 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 5243 1) 749 = true := by
  decide +kernel

theorem tr16014_8 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 5993 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 5992 1) 749 = true := by
  decide +kernel

theorem tr16014_9 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 6742 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 6741 1) 749 = true := by
  decide +kernel

theorem tr16014_10 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 7491 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 7490 1) 749 = true := by
  decide +kernel

theorem tr16014_11 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 8240 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 8239 1) 749 = true := by
  decide +kernel

theorem tr16014_12 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 8989 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 8988 1) 749 = true := by
  decide +kernel

theorem tr16014_13 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 9738 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 9737 1) 749 = true := by
  decide +kernel

theorem tr16014_14 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 10487 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 10486 1) 749 = true := by
  decide +kernel

theorem tr16014_15 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 11236 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 11235 1) 749 = true := by
  decide +kernel

theorem tr16014_16 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 11985 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 11984 1) 749 = true := by
  decide +kernel

theorem tr16014_17 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 12734 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 12733 1) 749 = true := by
  decide +kernel

theorem tr16014_18 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 13483 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 13482 1) 749 = true := by
  decide +kernel

theorem tr16014_19 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 14232 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 14231 1) 749 = true := by
  decide +kernel

theorem tr16014_20 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 14981 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 14980 1) 749 = true := by
  decide +kernel

theorem tr16014_21 : rangeOK 16014 16028 16 32124 ((2 ^ (32124 + 1) + 1) / 3) 15730 (powMod (2 ^ 32124) 64 ((2 ^ (32124 + 1) + 1) / 3) 15729 1) 285 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 16028` for the first two rises from every odd `n < 2^16014`. -/
theorem allPairs16014 : AllPairs 16014 16028 := allPairs_of_range ((((((((((((((((((((((rangeOK_sound tr16014_0).trans (rangeOK_sound tr16014_1)).trans (rangeOK_sound tr16014_2)).trans (rangeOK_sound tr16014_3)).trans (rangeOK_sound tr16014_4)).trans (rangeOK_sound tr16014_5)).trans (rangeOK_sound tr16014_6)).trans (rangeOK_sound tr16014_7)).trans (rangeOK_sound tr16014_8)).trans (rangeOK_sound tr16014_9)).trans (rangeOK_sound tr16014_10)).trans (rangeOK_sound tr16014_11)).trans (rangeOK_sound tr16014_12)).trans (rangeOK_sound tr16014_13)).trans (rangeOK_sound tr16014_14)).trans (rangeOK_sound tr16014_15)).trans (rangeOK_sound tr16014_16)).trans (rangeOK_sound tr16014_17)).trans (rangeOK_sound tr16014_18)).trans (rangeOK_sound tr16014_19)).trans (rangeOK_sound tr16014_20)).trans (rangeOK_sound tr16014_21))

end Collatz.TwoRise
