import Collatz.TwoRiseCheck

/-!
# Two-rise bounds for the chains of the `m`-cycle exclusions (kernel checks)

Generated by `research/scripts/mcycle101_certgen/gen_lean.py`. Each `AllPairs N B` is
`rangeOK` evaluated by the kernel on chunks of at most 3000 first rises
(`N` = 77, 103, 200, 322, 519, 759, 1111, 1789, 4217, 5613, 9040, 13235, 14558).
-/

set_option Elab.async false

namespace Collatz.TwoRise

theorem tr77_0 : rangeOK 77 84 16 250 ((2 ^ (250 + 1) + 1) / 3) 1 1 77 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 84` for the first two rises from every odd `n < 2^77`. -/
theorem allPairs77 : AllPairs 77 84 := allPairs_of_range (rangeOK_sound tr77_0)

theorem tr103_0 : rangeOK 103 107 16 302 ((2 ^ (302 + 1) + 1) / 3) 1 1 103 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 107` for the first two rises from every odd `n < 2^103`. -/
theorem allPairs103 : AllPairs 103 107 := allPairs_of_range (rangeOK_sound tr103_0)

theorem tr200_0 : rangeOK 200 206 16 496 ((2 ^ (496 + 1) + 1) / 3) 1 1 200 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 206` for the first two rises from every odd `n < 2^200`. -/
theorem allPairs200 : AllPairs 200 206 := allPairs_of_range (rangeOK_sound tr200_0)

theorem tr322_0 : rangeOK 322 328 16 740 ((2 ^ (740 + 1) + 1) / 3) 1 1 322 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 328` for the first two rises from every odd `n < 2^322`. -/
theorem allPairs322 : AllPairs 322 328 := allPairs_of_range (rangeOK_sound tr322_0)

theorem tr519_0 : rangeOK 519 526 16 1134 ((2 ^ (1134 + 1) + 1) / 3) 1 1 519 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 526` for the first two rises from every odd `n < 2^519`. -/
theorem allPairs519 : AllPairs 519 526 := allPairs_of_range (rangeOK_sound tr519_0)

theorem tr759_0 : rangeOK 759 766 16 1614 ((2 ^ (1614 + 1) + 1) / 3) 1 1 759 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 766` for the first two rises from every odd `n < 2^759`. -/
theorem allPairs759 : AllPairs 759 766 := allPairs_of_range (rangeOK_sound tr759_0)

theorem tr1111_0 : rangeOK 1111 1120 16 2318 ((2 ^ (2318 + 1) + 1) / 3) 1 1 1111 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 1120` for the first two rises from every odd `n < 2^1111`. -/
theorem allPairs1111 : AllPairs 1111 1120 := allPairs_of_range (rangeOK_sound tr1111_0)

theorem tr1789_0 : rangeOK 1789 1798 16 3674 ((2 ^ (3674 + 1) + 1) / 3) 1 1 1789 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 1798` for the first two rises from every odd `n < 2^1789`. -/
theorem allPairs1789 : AllPairs 1789 1798 := allPairs_of_range (rangeOK_sound tr1789_0)

theorem tr4217_0 : rangeOK 4217 4228 16 8530 ((2 ^ (8530 + 1) + 1) / 3) 1 1 2845 = true := by
  decide +kernel

theorem tr4217_1 : rangeOK 4217 4228 16 8530 ((2 ^ (8530 + 1) + 1) / 3) 2846 (powMod (2 ^ 8530) 64 ((2 ^ (8530 + 1) + 1) / 3) 2845 1) 1372 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 4228` for the first two rises from every odd `n < 2^4217`. -/
theorem allPairs4217 : AllPairs 4217 4228 := allPairs_of_range ((rangeOK_sound tr4217_0).trans (rangeOK_sound tr4217_1))

theorem tr5613_0 : rangeOK 5613 5626 16 11322 ((2 ^ (11322 + 1) + 1) / 3) 1 1 2137 = true := by
  decide +kernel

theorem tr5613_1 : rangeOK 5613 5626 16 11322 ((2 ^ (11322 + 1) + 1) / 3) 2138 (powMod (2 ^ 11322) 64 ((2 ^ (11322 + 1) + 1) / 3) 2137 1) 2137 = true := by
  decide +kernel

theorem tr5613_2 : rangeOK 5613 5626 16 11322 ((2 ^ (11322 + 1) + 1) / 3) 4275 (powMod (2 ^ 11322) 64 ((2 ^ (11322 + 1) + 1) / 3) 4274 1) 1339 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 5626` for the first two rises from every odd `n < 2^5613`. -/
theorem allPairs5613 : AllPairs 5613 5626 := allPairs_of_range (((rangeOK_sound tr5613_0).trans (rangeOK_sound tr5613_1)).trans (rangeOK_sound tr5613_2))

theorem tr9040_0 : rangeOK 9040 9054 16 18176 ((2 ^ (18176 + 1) + 1) / 3) 1 1 1327 = true := by
  decide +kernel

theorem tr9040_1 : rangeOK 9040 9054 16 18176 ((2 ^ (18176 + 1) + 1) / 3) 1328 (powMod (2 ^ 18176) 64 ((2 ^ (18176 + 1) + 1) / 3) 1327 1) 1327 = true := by
  decide +kernel

theorem tr9040_2 : rangeOK 9040 9054 16 18176 ((2 ^ (18176 + 1) + 1) / 3) 2655 (powMod (2 ^ 18176) 64 ((2 ^ (18176 + 1) + 1) / 3) 2654 1) 1327 = true := by
  decide +kernel

theorem tr9040_3 : rangeOK 9040 9054 16 18176 ((2 ^ (18176 + 1) + 1) / 3) 3982 (powMod (2 ^ 18176) 64 ((2 ^ (18176 + 1) + 1) / 3) 3981 1) 1327 = true := by
  decide +kernel

theorem tr9040_4 : rangeOK 9040 9054 16 18176 ((2 ^ (18176 + 1) + 1) / 3) 5309 (powMod (2 ^ 18176) 64 ((2 ^ (18176 + 1) + 1) / 3) 5308 1) 1327 = true := by
  decide +kernel

theorem tr9040_5 : rangeOK 9040 9054 16 18176 ((2 ^ (18176 + 1) + 1) / 3) 6636 (powMod (2 ^ 18176) 64 ((2 ^ (18176 + 1) + 1) / 3) 6635 1) 1327 = true := by
  decide +kernel

theorem tr9040_6 : rangeOK 9040 9054 16 18176 ((2 ^ (18176 + 1) + 1) / 3) 7963 (powMod (2 ^ 18176) 64 ((2 ^ (18176 + 1) + 1) / 3) 7962 1) 1078 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 9054` for the first two rises from every odd `n < 2^9040`. -/
theorem allPairs9040 : AllPairs 9040 9054 := allPairs_of_range (((((((rangeOK_sound tr9040_0).trans (rangeOK_sound tr9040_1)).trans (rangeOK_sound tr9040_2)).trans (rangeOK_sound tr9040_3)).trans (rangeOK_sound tr9040_4)).trans (rangeOK_sound tr9040_5)).trans (rangeOK_sound tr9040_6))

theorem tr13235_0 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 1 1 906 = true := by
  decide +kernel

theorem tr13235_1 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 907 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 906 1) 906 = true := by
  decide +kernel

theorem tr13235_2 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 1813 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 1812 1) 906 = true := by
  decide +kernel

theorem tr13235_3 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 2719 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 2718 1) 906 = true := by
  decide +kernel

theorem tr13235_4 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 3625 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 3624 1) 906 = true := by
  decide +kernel

theorem tr13235_5 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 4531 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 4530 1) 906 = true := by
  decide +kernel

theorem tr13235_6 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 5437 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 5436 1) 906 = true := by
  decide +kernel

theorem tr13235_7 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 6343 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 6342 1) 906 = true := by
  decide +kernel

theorem tr13235_8 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 7249 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 7248 1) 906 = true := by
  decide +kernel

theorem tr13235_9 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 8155 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 8154 1) 906 = true := by
  decide +kernel

theorem tr13235_10 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 9061 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 9060 1) 906 = true := by
  decide +kernel

theorem tr13235_11 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 9967 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 9966 1) 906 = true := by
  decide +kernel

theorem tr13235_12 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 10873 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 10872 1) 906 = true := by
  decide +kernel

theorem tr13235_13 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 11779 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 11778 1) 906 = true := by
  decide +kernel

theorem tr13235_14 : rangeOK 13235 13248 16 26566 ((2 ^ (26566 + 1) + 1) / 3) 12685 (powMod (2 ^ 26566) 64 ((2 ^ (26566 + 1) + 1) / 3) 12684 1) 551 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 13248` for the first two rises from every odd `n < 2^13235`. -/
theorem allPairs13235 : AllPairs 13235 13248 := allPairs_of_range (((((((((((((((rangeOK_sound tr13235_0).trans (rangeOK_sound tr13235_1)).trans (rangeOK_sound tr13235_2)).trans (rangeOK_sound tr13235_3)).trans (rangeOK_sound tr13235_4)).trans (rangeOK_sound tr13235_5)).trans (rangeOK_sound tr13235_6)).trans (rangeOK_sound tr13235_7)).trans (rangeOK_sound tr13235_8)).trans (rangeOK_sound tr13235_9)).trans (rangeOK_sound tr13235_10)).trans (rangeOK_sound tr13235_11)).trans (rangeOK_sound tr13235_12)).trans (rangeOK_sound tr13235_13)).trans (rangeOK_sound tr13235_14))

theorem tr14558_0 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 1 1 824 = true := by
  decide +kernel

theorem tr14558_1 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 825 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 824 1) 824 = true := by
  decide +kernel

theorem tr14558_2 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 1649 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 1648 1) 824 = true := by
  decide +kernel

theorem tr14558_3 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 2473 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 2472 1) 824 = true := by
  decide +kernel

theorem tr14558_4 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 3297 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 3296 1) 824 = true := by
  decide +kernel

theorem tr14558_5 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 4121 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 4120 1) 824 = true := by
  decide +kernel

theorem tr14558_6 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 4945 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 4944 1) 824 = true := by
  decide +kernel

theorem tr14558_7 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 5769 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 5768 1) 824 = true := by
  decide +kernel

theorem tr14558_8 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 6593 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 6592 1) 824 = true := by
  decide +kernel

theorem tr14558_9 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 7417 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 7416 1) 824 = true := by
  decide +kernel

theorem tr14558_10 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 8241 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 8240 1) 824 = true := by
  decide +kernel

theorem tr14558_11 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 9065 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 9064 1) 824 = true := by
  decide +kernel

theorem tr14558_12 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 9889 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 9888 1) 824 = true := by
  decide +kernel

theorem tr14558_13 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 10713 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 10712 1) 824 = true := by
  decide +kernel

theorem tr14558_14 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 11537 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 11536 1) 824 = true := by
  decide +kernel

theorem tr14558_15 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 12361 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 12360 1) 824 = true := by
  decide +kernel

theorem tr14558_16 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 13185 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 13184 1) 824 = true := by
  decide +kernel

theorem tr14558_17 : rangeOK 14558 14573 16 29212 ((2 ^ (29212 + 1) + 1) / 3) 14009 (powMod (2 ^ 29212) 64 ((2 ^ (29212 + 1) + 1) / 3) 14008 1) 550 = true := by
  decide +kernel

/-- `k₀ + k₁ ≤ 14573` for the first two rises from every odd `n < 2^14558`. -/
theorem allPairs14558 : AllPairs 14558 14573 := allPairs_of_range ((((((((((((((((((rangeOK_sound tr14558_0).trans (rangeOK_sound tr14558_1)).trans (rangeOK_sound tr14558_2)).trans (rangeOK_sound tr14558_3)).trans (rangeOK_sound tr14558_4)).trans (rangeOK_sound tr14558_5)).trans (rangeOK_sound tr14558_6)).trans (rangeOK_sound tr14558_7)).trans (rangeOK_sound tr14558_8)).trans (rangeOK_sound tr14558_9)).trans (rangeOK_sound tr14558_10)).trans (rangeOK_sound tr14558_11)).trans (rangeOK_sound tr14558_12)).trans (rangeOK_sound tr14558_13)).trans (rangeOK_sound tr14558_14)).trans (rangeOK_sound tr14558_15)).trans (rangeOK_sound tr14558_16)).trans (rangeOK_sound tr14558_17))

end Collatz.TwoRise
