import Collatz.MCycleSteps
import Collatz.MCycleTwoRiseLo

/-!
# Two-rise bounds for the chains: the grid `gridLo` (35 values of `N`)

Generated by `research/scripts/mcycle101_certgen/gen_lean.py`.
-/

namespace Collatz

/-- The two-rise bounds `(N, B)` (increasing `N`). -/
def gridLo : List (ℕ × ℕ) := [(72, 84),
    (73, 84),
    (74, 84),
    (75, 84),
    (76, 84),
    (114, 120),
    (115, 120),
    (116, 120),
    (117, 124),
    (118, 124),
    (119, 124),
    (120, 125),
    (121, 127),
    (122, 128),
    (123, 128),
    (187, 194),
    (188, 196),
    (189, 196),
    (190, 196),
    (191, 196),
    (193, 197),
    (194, 199),
    (195, 200),
    (196, 206),
    (301, 308),
    (304, 310),
    (306, 313),
    (310, 318),
    (314, 321),
    (315, 322),
    (483, 491),
    (487, 495),
    (501, 512),
    (775, 782),
    (799, 805)]

theorem gridLo_cons {e₀ : ℕ × ℕ} {l : List (ℕ × ℕ)} (h₀ : TwoRiseBound e₀.1 e₀.2)
    (hl : ∀ e ∈ l, TwoRiseBound e.1 e.2) : ∀ e ∈ e₀ :: l, TwoRiseBound e.1 e.2 := by
  intro e he
  rcases List.mem_cons.mp he with h | h
  · rw [h]; exact h₀
  · exact hl e h

theorem gridLo_nil : ∀ e ∈ ([] : List (ℕ × ℕ)), TwoRiseBound e.1 e.2 := by
  intro e he
  cases he

theorem gridLo_ok : ∀ e ∈ gridLo, TwoRiseBound e.1 e.2 := by
  unfold gridLo
  exact gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs72) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs73) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs74) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs75) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs76) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs114) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs115) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs116) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs117) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs118) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs119) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs120) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs121) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs122) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs123) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs187) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs188) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs189) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs190) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs191) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs193) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs194) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs195) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs196) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs301) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs304) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs306) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs310) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs314) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs315) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs483) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs487) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs501) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs775) <|
    gridLo_cons (twoRiseBound_of_allPairs TwoRise.allPairs799) <|
    gridLo_nil

end Collatz
